### ISSUE TITLE
[Feature] Choose sound output device for each application

### ISSUE THREAD

**Issue by Janhouse** [Rayzeq/quick-settings-audio-panel#10]
This is just a feature request to be able to choose sound output device per application from the quick settings panel.

**Comment by Janhouse** [comment]
Visually it could probably look the same as output device chooser. 
![image](https://github.com/Rayzeq/quick-settings-audio-panel/assets/1036439/b3088caf-f939-4999-acbe-4b070e4db6c5)

**Comment by Rayzeq** [comment]
I need to fix the popups before I can do that. I'm already working on it, but I can't really give an ETA.

**Comment by Rayzeq** [comment]
This is implemented in the latest commit. However, it will probably be some time before it is available on e.g.o as libpanel needs to pass the review.

**Comment by Janhouse** [comment]
@Rayzeq great work!

I had to pull it from git to try out. :slightly_smiling_face: 
Maybe the layout looks a bit weird since the arrow on the right side understandably doesn't align with slider but it works great.

And it might be a good idea to have this feature toggle-able in settings since not everyone might want that.

![image](https://github.com/Rayzeq/quick-settings-audio-panel/assets/1036439/f1509d40-65b6-49a4-876c-9a20e7e9f171)

IMHO Gnome should already come with something like this out of the box, but they probably won't.

**Comment by Rayzeq** [comment]
I've fixed the arrow alignment issue (in the last commit) and agree it's better. I've also made the icon button round (it no longer stretches vertically to fill the space) and I'd like to know what you think.
I don't think it's really necessary to make it an option as people who don't need it probably don't have multiple audio outputs anyway, so the arrow doesn't appear.

**Comment by Janhouse** [comment]
Alignment looking good now. :+1: 

Yes, I guess user can disable unnecessary audio devices in pavucontrol. But they tend to pop up when plugging in hdmi monitors and some other devices. Up to you if you want this as a setting, since I personally will keep this feature enabled at all times. :smile:

**Comment by NA0341** [comment]
@Rayzeq I want to show my Deepest Gratitude to You :pray:  Your Extension is Great! 🎉

And especially **This feature!**
I've spent so much time already searching for Software which would allow me to Quickly Change Output Devices for Individual Applications.
And now I just stumbled across your great extension in Extension Manager.

There's one issue though ~ for which I created a new card here: #47
