### ISSUE TITLE
[Feature] Possibility to positon media controls next to corresponding application mixer

### ISSUE THREAD

**Issue by Janhouse** [Rayzeq/quick-settings-audio-panel#16]
It would be cool to have an option to position media controls next to the corresponding application volume controls slider.
Or maybe even put the volume slider inside media controls box.

Of course the tricky part is linking streams with media player objects (org.mpris.MediaPlayer2). Dbus does indicate the owner attribute which appears to contain application name, so this could be used for linking, but not sure if it is easily accessible [from the js side currently](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/mpris.js). It probably can be figured out but would require some looking into it.

Also seems like each application can have [only one mpris player](https://stackoverflow.com/a/44799664) but there can be multiple mixers per application. In real world this is probably not a real issue but it could look weird for some edge cases where there is only one player box but multiple volume sliders. :smile: 

Feel free to close this if you think it makes no sense whatsoever.

**Comment by Rayzeq** [comment]
As you said, this could be difficult to implement. In addition to the problems you've already mentioned, there's also the fact that all the mixer sliders are grouped together, as are the mpris controls. Separating the sliders wouldn't be too difficult, but separating the mpris controls wouldn't be so easy, I think.

**Comment by Rayzeq** [comment]
I'm not opposed to the idea of doing that but I'll do it after fixing the popups

**Comment by Rayzeq** [comment]
Having looked into it, it doesn't really seem possible. The main issue is that there is no good way of linking streams with mpris controls.
For some applications, it's easy (e.g. ncspot uses `ncspot` for its stream and `org.mpris.MediaPlayer2.ncspot` for its mpris controls), but for others it is virtually impossible (e.g. opera uses `Opera` for its stream and `org.mpris.MediaPlayer2.chromium.instance481092` for its mpris controls).
