### ISSUE TITLE
stream.name is null in v14

### ISSUE THREAD

**Issue by Janhouse** [Rayzeq/quick-settings-audio-panel#18]
![image](https://github.com/Rayzeq/quick-settings-audio-panel/assets/1036439/7eeec0ab-707b-4ba6-a302-b024a7a8f9f1)

Gnome auto-updated extension to v14 and it doesn't work at all.

**Comment by Rayzeq** [comment]
That's strange, it works fine for me. Could you post the logs (using `journalctl -f -o cat /usr/bin/gnome-shell`) so I can get a better idea of what's going on ?

**Comment by Rayzeq** [comment]
Never mind, it's a regression of a bug you fixed earlier, I fixed it.
