### ISSUE TITLE
Bug new version of the extension

### ISSUE THREAD

**Issue by tachyglossues** [Rayzeq/quick-settings-audio-panel#21]
Hi,

I've encountered a problem with this extension which stopped working after the last update. I get this error "item.menu._signalConnectionsByName is undefined". What's more, the top right-hand panel doesn't open either (and it works again when I remove the extension).

**Comment by Ticklezz** [comment]
I saw the same thing and had to remove the extension as it broke the pull down menu and killed some other extensions.

**Comment by bern6** [comment]
I confirm this bug.

**Comment by Rayzeq** [comment]
I've published a patch (version 20). However, I don't really know the cause of the issue. Could you tell me what version of gnome shell you have, and what extensions you have installed?

**Comment by tachyglossues** [comment]
> I've published a patch (version 20). However, I don't really know the cause of the issue. Could you tell me what version of gnome shell you have, and what extensions you have installed?

The patch works, I use gnome 44.1 with wayland. I also use : 
reminder_alarm_clock@trifonovkv.gmail.com
rocketbar@chepkun.github.com
volume_scroller@trflynn89.pm.me
just-perfection-desktop@just-perfection
pwcalc@thilomaurer.de
pano@elhan.io
battery-indicator-icon@Deminder
batterytime@typeof.pw
grand-theft-focus@zalckos.github.com
colorblind-filters@G-dH.github.com
AlphabeticalAppGrid@stuarthayhurst
color-picker@tuberry
quick-settings-audio-panel@rayzeq.github.io
ubuntu-appindicators@ubuntu.com
tiling-assistant@leleat-on-github
native-window-placement@gnome-shell-extensions.gcampax.github.com
screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com
user-theme@gnome-shell-extensions.gcampax.github.com
workspace-indicator@gnome-shell-extensions.gcampax.github.com

And I suppose that rocketbar or just-perfection may be in conflict, so good luck figuring out the bug.

**Comment by Ticklezz** [comment]
![Screenshot from 2023-07-09 15-33-57](https://github.com/Rayzeq/quick-settings-audio-panel/assets/113319295/7e73a313-ddb6-4ac7-a2df-d74e34d408f9)
I installed new version and it's working yet i have this.

**Comment by Ticklezz** [comment]
I use these extensions. I am on gnome 43.4
![Screenshot from 2023-07-09 15-37-46](https://github.com/Rayzeq/quick-settings-audio-panel/assets/113319295/6b73461e-537e-42db-a302-379aa6e38e9c)
![Screenshot from 2023-07-09 15-38-03](https://github.com/Rayzeq/quick-settings-audio-panel/assets/113319295/281b66d7-88f3-4636-9eec-88d06670f99c)
![Screenshot from 2023-07-09 15-38-33](https://github.com/Rayzeq/quick-settings-audio-panel/assets/113319295/85bec451-03f5-42a0-860f-1ac27f10699e)

**Comment by Rayzeq** [comment]
That's a lot of extensions 😅.
@Ticklezz, I hadn't thought about the fact that not everyone has `pactl`. I've just fixed it in version 21 (available soon), however you won't be able to change the output device for each stream in the mixer. If you want this feature, you'll need to install pactl.

**Comment by Ticklezz** [comment]
> That's a lot of extensions sweat_smile. @Ticklezz, I hadn't thought about the fact that not everyone has `pactl`. I've just fixed it in version 21 (available soon), however you won't be able to change the output device for each stream in the mixer. If you want this feature, you'll need to install pactl.

Yeah it just somehow blew up to this many. It's a risky slope to be on.

**Comment by Ticklezz** [comment]
> That's a lot of extensions sweat_smile. @Ticklezz, I hadn't thought about the fact that not everyone has `pactl`. I've just fixed it in version 21 (available soon), however you won't be able to change the output device for each stream in the mixer. If you want this feature, you'll need to install pactl.

I am on pipewire so not sure i would need patcl really.

**Comment by Rayzeq** [comment]
> I am on pipewire so not sure i would need patcl really.

The extension must use pactl because gnome-volume-control is missing some features. I also use pipewire, but pactl still works (not pacmd though).
But if you don't need that feature, you don't need pactl. Btw it's this menu that will be disabled :
![](https://user-images.githubusercontent.com/1036439/251971204-f1509d40-65b6-49a4-876c-9a20e7e9f171.png)

**Comment by Rayzeq** [comment]
@tachyglossues I did a quick review of all the extensions you have and couldn't find the source of the issue. But as it works anyway, I don't think I'll be looking any further.
