### ISSUE TITLE
Volume slider and media control is at the bottom of the screen

### ISSUE THREAD

**Issue by AshtakaOOf** [Rayzeq/quick-settings-audio-panel#22]
This started happening with the last update
Fedora 38 Workstation, Gnome 44.2

![image](https://github.com/Rayzeq/quick-settings-audio-panel/assets/66513643/6fbf7952-b7f9-4aa3-88af-b5298248354d)

The extensions I use that might have changed the quicksettings are [Caffeine](https://github.com/eonpatapon/gnome-shell-extension-caffeine), [supergfxctl-gex](https://gitlab.com/asus-linux/supergfxctl-gex) and [Quick Settings Avatar](https://github.com/d-go/quick-settings-avatar)

**Comment by Rayzeq** [comment]
Are you sure you're on the latest version (version 20)? It should have corrected this issue.

**Comment by AshtakaOOf** [comment]
> Are you sure you're on the latest version (version 20)? It should have corrected this issue.

Sorry for replying late, I am on version 20 and it seems there's a new version called 21?

**Comment by AshtakaOOf** [comment]
21 seems to fix the bug at least right now.

**Comment by Rayzeq** [comment]
It's version 21 that fixes this issue, however version 20 contains a workaround that should prevent this bug from happening, so I'm not really sure why it didn't work. But if it works with version 21, I guess it's fixed. Feel free to reopen the issue if the bug reappears.
