### ISSUE TITLE
this._control.lookup_device_from_stream(...) is null

### ISSUE THREAD

**Issue by jorge-a-goncalves** [Rayzeq/quick-settings-audio-panel#26]
I am getting error this._control.lookup_device_from_stream(...) is null
![image](https://github.com/Rayzeq/quick-settings-audio-panel/assets/118197475/0fffe4b3-28c5-4868-a64e-8be2c204bf94)

I believe this started after installing something with audio, maybe pulse audio related or something. 

Although it gives an error and it says it's turned off, it still seems to works. But not the mixer part.  
![image](https://github.com/Rayzeq/quick-settings-audio-panel/assets/118197475/b9971340-1b0a-43fa-a530-e72911b0384d)

I am on Nobara 38, Gnome 44.2, Wayland, Linux 6.5.5

**Comment by Rayzeq** [comment]
I've posted a patched version (32).
The fix just prevents the extension from crashing, but does nothing more, so you may not be able to change the output device for each application individually.

**Comment by jorge-a-goncalves** [comment]
Not only did it fixe the extension form crashing but I can now change the output device for each application individually.
Its perfect, thank you.
