### ISSUE TITLE
this.menu.insertItemBefore is not a function

### ISSUE THREAD

**Issue by RockClapps** [Rayzeq/quick-settings-audio-panel#27]
For whatever reason, this extension seems to break other extensions that add a menu item to the quick-settings menu on Gnome 45

## How to reproduce
1. Install this extension and an extension that adds something to the quick-settings menu
    - Example: Caffine https://extensions.gnome.org/extension/517/caffeine/
    - Example: Forge https://extensions.gnome.org/extension/4481/forge/
2. Upon login, the other extension will report a `this.menu.insertItemBefore is not a function` error.

**Comment by Rayzeq** [comment]
Compatibility with both of these extensions is now fixed in version 33
