### ISSUE TITLE
YouTube audio level for Flatpak Firefox defaults to 100% when video position is changed

### ISSUE THREAD

**Issue by incentivebeats** [Rayzeq/quick-settings-audio-panel#29]
If I'm watching a video on YouTube, and the audio level for the Firefox channel is set to 50%, the level will return to 100% after skipping the video ahead or behind.

This only happens with YouTube. I've tested with other sites like Soundcloud and Bandcamp and the audio level is respected when the position is changed. 

Using Firefox via Flatpak. Arch Linux with GNOME 45.

**Comment by Rayzeq** [comment]
From what you've said, I don't think it's related to my extension. I can't really see what would cause such a problem in my extension (mainly because I'm just using slightly modified gnome components for the mixer).
Does the issue disappear when you disable the extension ?

**Comment by TheNexter** [comment]
> From what you've said, I don't think it's related to my extension. I can't really see what would cause such a problem in my extension (mainly because I'm just using slightly modified gnome components for the mixer). Does the issue disappear when you disable the extension ?

I confirm, this is not about the extension. If you talk about youtube SHORT, this is normal, the sound volume is base on your volume from latest video you watch
