### ISSUE TITLE
Power menu remains expanded after waking up PC from suspension

### ISSUE THREAD

**Issue by caesarw** [Rayzeq/quick-settings-audio-panel#30]
Steps to reproduce:
1. Suspend the PC by clicking the top-right menu -> power icon -> Suspend
2. Wake up the PC
3. Click to expand the top-right menu again
4. The power menu remains expanded (but without focus, indicating a bug, see screenshot below)
![The buggy expanded power menu when bug occurs](https://github.com/Rayzeq/quick-settings-audio-panel/assets/11749340/f015fd3d-6d92-42ba-9bc2-80373815438d)

Expected behavior:
After waking up the PC, the power menu should not be expanded, nor expanded without focus. 

I have tried the following to make sure the bug is indeed caused by this extension:
1. Disable GNOME Extension completely. The bug cannot be reproduced.
2. Enable all used extensions except Quick Settings Audio Panel. The bug cannot be reproduced.
3. Disable all used extensions except Quick Settings Audio Panel. The bug was reproduced.

**Comment by Rayzeq** [comment]
This is fixed by version 34. Do note that this version is for gnome 45, if you're using gnome 44 please let me know so I also make a release for this version.

**Comment by caesarw** [comment]
Just tested and can confirm this is fixed. Thanks a lot dev!
