### ISSUE TITLE
Enabling extension: Error (this._iconButton is undefined)

### ISSUE THREAD

**Issue by cweiske** [Rayzeq/quick-settings-audio-panel#32]
I am running Gnome Shell 43.9 on Debian 12.4. When enabling the extension on https://extensions.gnome.org/extension/5940/quick-settings-audio-panel/ I get a red "ERROR" where the "enable" button was.

My journal shows:
```
gnome-shell[5892]:
JS ERROR: Extension quick-settings-audio-panel@rayzeq.github.io: TypeError: this._iconButton is undefined
@/home/cweiske/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/libs/widgets.js:126:9
_stream_added@/home/cweiske/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/libs/widgets.js:50:24
ApplicationsMixer@/home/cweiske/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/libs/widgets.js:29:18
_create_app_mixer@/home/cweiske/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/extension.js:194:36
_refresh_panel@/home/cweiske/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/extension.js:125:26
enable@/home/cweiske/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/extension.js:66:14
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:184:32
_onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:529:35
_onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:529:14
createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:686:46
enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:211:29
_onInstallButtonPressed@resource:///org/gnome/shell/ui/extensionDownloader.js:268:40
Async*addButton/<@resource:///org/gnome/shell/ui/dialog.js:130:41
```

**Comment by Rayzeq** [comment]
Are you using any other extension beside QSAP, and if yes, which one ?
It's probably a compatibility issue with an extension that replaces the output / input volume sliders with its own version.

**Comment by cweiske** [comment]
I use:
- AppIndicator andKStatusNotifierItem Support, v53
- Desktop Icons NG (DING), v63
- Workspace Scroll, v3.0.0
- Applications Menu, 43.1-1 (debian package)
- User Themes, 43.1-1 (debian package)
- Window List, 43.1-1 (debian package)

Simply disabling all the other extensions and trying to reinstall QSAP does not work. Maybe I have to log off and in again.

**Comment by Rayzeq** [comment]
```
[LibPanel] quick-settings-audio-panel@rayzeq.github.io tried to remove an item not in the panel
[LibPanel] quick-settings-audio-panel@rayzeq.github.io tried to remove an item not in the panel
```
This indicates that something went really wrong. Either another extension is moving around parts of the ui (maybe Window List or Applications Menu, but I don't think it's the case), or you broke something by disabling / re-enabling extensions.

Please try to log out and in again with only QSAP enabled. If the issue don't appear, please try to enable your extensions one by one to find which one is incompatible.

**Comment by cweiske** [comment]
Logging out and in again made the problem go away.
All other extensions are still enabled.
Sorry for the noise.

**Comment by cweiske** [comment]
The log entry is still there, even though the extension itself works.

It happens when an audio playing application is started, and the application mixer is not visible:
```
Jan 25 16:42:23 pixy systemd[5666]: Started app-gnome-org.gnome.Rhythmbox3-1250997.scope - Application launched by gnome-shell.
Jan 25 16:42:27 pixy gnome-shell[1240451]: JS ERROR: TypeError: this._iconButton is undefined
                                           @/home/cweiske/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/libs/widgets.js:126:9
                                           _stream_added@/home/cweiske/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/libs/widgets.js:50:24
Jan 25 16:42:27 pixy gnome-shell[1240451]: JS ERROR: TypeError: this._iconButton is undefined
                                           @/home/cweiske/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/libs/widgets.js:126:9
                                           _stream_added@/home/cweiske/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/libs/widgets.js:50:24
```

**Comment by cweiske** [comment]
There is no `_iconButton` in gnome shell 43.9:
- main: https://gitlab.gnome.org/search?search=_iconButton&nav_source=navbar&project_id=546&group_id=8&search_code=true&repository_ref=main
- 43.9: https://gitlab.gnome.org/search?search=_iconButton&nav_source=navbar&project_id=546&group_id=8&search_code=true&repository_ref=43.9

**Comment by Rayzeq** [comment]
Well, it look like this issue was introduced in v19 and nobody noticed, probably because there is not many people still using gnome 43. It will be fixed in the next version, which should be released quickly.
