### ISSUE TITLE
Multiple output volume sliders

### ISSUE THREAD

**Issue by cweiske** [Rayzeq/quick-settings-audio-panel#34]
I'm listening to music on my "normal" speakers, but use a USB headset for video conferences and calls.
Currently I can only control the output volume of the default output.

It would be nice if I could have volume sliders for both outputs.

(This is on Quick Settings Audio Panel v32.)

**Comment by Rayzeq** [comment]
I made this feature for gnome 45 and backported it to gnome 43/44, but I can't test it on those version because I use gnome 45 and my vm is broken. Could test if everything works correctly with this version [quick-settings-audio-panel@rayzeq.github.io.shell-extension.zip](https://github.com/Rayzeq/quick-settings-audio-panel/files/14062917/quick-settings-audio-panel%40rayzeq.github.io.shell-extension.zip) ? (you can find instructions to install it on the readme)

**Comment by cweiske** [comment]
Unfortunately not:
```
gnome-shell[3192]: JS ERROR: ReferenceError: SinkVolumeSlider is not defined
_stream_added@/home/cweiske/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/libs/widgets.js:126:24
SinkMixer@/home/cweiske/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/libs/widgets.js:105:18
_create_sink_mixer@/home/cweiske/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/extension.js:211:28
_refresh_panel@/home/cweiske/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/extension.js:132:26
enable/this._sc_callback<@/home/cweiske/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/extension.js:65:73
```

**Comment by Rayzeq** [comment]
I hope I didn't forgot anything in this one
[quick-settings-audio-panel@rayzeq.github.io.shell-extension.zip](https://github.com/Rayzeq/quick-settings-audio-panel/files/14065880/quick-settings-audio-panel%40rayzeq.github.io.shell-extension.zip)

**Comment by cweiske** [comment]
It works! Thank you very much.
![2024-01-29 output slider](https://github.com/Rayzeq/quick-settings-audio-panel/assets/59036/b6db4884-0d36-422e-8abd-cd314312bb1b)

Disabling the main volume slider (output slider) did not work at first, I had to enable and disable other settings until it worked.
When it failed I had the following message in the log:
```
gnome-shell[6274]: JS ERROR: ReferenceError: can't access lexical declaration '_' before initialization
ApplicationVolumeSlider@/home/cweiske/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/libs/widgets.js:215:9
_stream_added@/home/cweiske/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/libs/widgets.js:51:24
ApplicationsMixer@/home/cweiske/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/libs/widgets.js:30:18
_create_app_mixer@/home/cweiske/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/extension.js:207:36
_refresh_panel@/home/cweiske/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/extension.js:130:26
enable/this._sc_callback<@/home/cweiske/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/extension.js:65:73
```

**Comment by Rayzeq** [comment]
I'm even surprised it worked :), but this should be the last fix, I'll publish it to e.g.o, but you can also have it here.
[quick-settings-audio-panel@rayzeq.github.io.shell-extension.zip](https://github.com/Rayzeq/quick-settings-audio-panel/files/14083065/quick-settings-audio-panel%40rayzeq.github.io.shell-extension.zip)
Please close this issue if you don't see any other problems.

**Comment by cweiske** [comment]
It works fine now. Thank you very much, @Rayzeq.
