### ISSUE TITLE
The changes to Gnome Shell through the extension does not stay. Have to disable and enale extension

### ISSUE THREAD

**Issue by gorbehnare** [Rayzeq/quick-settings-audio-panel#37]
Hello

I am not sure if this is a problem with Gnome, my installation, or this extension. 

I use this extension to display the input volume slider as well as the output slider. I want this to stay permanently regardless of when devices are added or removed so I can change input/output quickly without having to open the settings. 

Unfortunately, the input slider keeps disappearing as soon as I try to change input, or as soon as some change happens (such as plugging in a headphone, etc). 

Example: 
![image](https://github.com/Rayzeq/quick-settings-audio-panel/assets/13162106/445a12a8-854d-4e5c-a626-6d75c0de55a6)

Then I try to select a different input:
![image](https://github.com/Rayzeq/quick-settings-audio-panel/assets/13162106/0ed3f9e6-7efd-4a19-8079-7350e74ce043)

The slider disappears immediately:
![image](https://github.com/Rayzeq/quick-settings-audio-panel/assets/13162106/957b3cf9-851a-4457-a895-6ac89f560353)

I have to toggle the extension to get it back. 

I asked the Gnome public matrix room, and it looks like they rely heavily on extensions to do these little things (which is very odd and stupid to not have a built-in way of changing settings for this kind of thing, but what do I know, I'l just an end-user). 

Please let me know if there are any logs or other information I can provide.

**Comment by Rayzeq** [comment]
This was an issue with the extension, which sometimes didn't show the slider when it was hidden by gnome. It is fixed in the latest version.

**Comment by gorbehnare** [comment]
Thank you for your quick response.
