### ISSUE TITLE
Add support for GNOME 46

### ISSUE THREAD

**Issue by Ciberbago** [Rayzeq/quick-settings-audio-panel#39]
Hello! First I'd like to thank you for this extension, is pretty useful to me.
Second... I would like to know if it's possible for you to add support for the latest gnome 46 version.
I tried to disable the extension version validation parameter and this is the error this extensions gives me:

 Error: No signal 'actor-added' on object 'LibPanel_PanelColumn_quick-settings-audio-panel-rayzeq-github-io'

**Comment by Facni** [comment]
+1

**Comment by Rayzeq** [comment]
Version 46 adds support for gnome 46, however I haven't tested it extensively so there may be some issues but it seems to work
