### ISSUE TITLE
Adding labels to input/output sliders? 

### ISSUE THREAD

**Issue by kabe-inc** [Rayzeq/quick-settings-audio-panel#41]
Hi, thanks for this great extension - I have multiple audio devices and it makes it so much easier to switch between them on the fly.

I do have a feature request, though: Would it be possible to add the option of adding a label to the input/output devices so the user can see which ones are active at a glance without having to click the expansion arrows?

I'm imagining something like this:

![Screenshot from 2024-05-01 09-42-45](https://github.com/Rayzeq/quick-settings-audio-panel/assets/72587902/f1c3cdaf-13af-4492-8532-556871f26d4f)

**Comment by Rayzeq** [comment]
I made this feature and released it as version 47 (gnome 46) and version 48 (gnome 45). I don't plan on releasing a gnome 43/44 version because I believe it's not used a lot anymore, however if you (or anyone else) want it, say it there and I'll make a backport.

**Comment by kabe-inc** [comment]
> I made this feature and released it as version 47 (gnome 46) and version 48 (gnome 45). I don't plan on releasing a gnome 43/44 version because I believe it's not used a lot anymore, however if you (or anyone else) want it, say it there and I'll make a backport.

I am on Gnome 46, though. Is there a toggle option or something I'm missing?

**Comment by kabe-inc** [comment]
Ok, so there appears to be an issue with the latest release. It seems to be reverting to version 46, for some reason?

What occurred for me

1. Uninstalled version 46 using Extensions Manager
2. Flash installed version 47 of `quick-settings-audio-panel@rayzeq.github.io.shell-extension.zip` using `gnome-extensions install -f quick-settings-audio-panel@rayzeq.github.io.shell-extension.zip'
3. Log out and in again
4.  Get update notification from Extension Manager even though version 47 is confirmed in ~/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/metadata.json
5. Log out and in again
6. Extensions has reverted back to v46.

I should also note that when v47 was installed, I could see no labels on the devices, nor was there an option in the settings to toggle them on/off.

P.S. I'm on Arch btw.

**Comment by Rayzeq** [comment]
I did some tests and had the same issue, however I have no idea why, my best guess is that the latest version from gnome's website is considered the latest version, even if the installed version is newer.
The only way I've found to “fix” the issue is to uninstall `gnome-shell-extension-manager` (that's the Ubuntu package name, it's probably different on Arch), but if you're patient, the problem should fix itself when v47 is reviewed on the website (it's usually pretty quick).

The new feature is disabled by default and must be enabled in the settings. It's strange that you didn't see the option, it was present for me when v47 was installed:
![image](https://github.com/Rayzeq/quick-settings-audio-panel/assets/26172375/a793a639-250c-47b7-a384-65f7e0e7a8d8)

**Comment by kabe-inc** [comment]
Ok, thanks very much. I'll wait for the update and report back if there any issues.

**Comment by kabe-inc** [comment]
Hey, just wanted to report back that the update fixed the above issues, so thanks again for that.

There is one thing I ought to mention, though - I am also using the [Quicksettings Audio Devices Renamer](https://github.com/marcinjahn/gnome-quicksettings-audio-devices-renamer-extension) extension, and was wondering how difficult it would to add cross-compatibility to your extension as well?

Reason being, anyone using both is going to see their custom names used in the sound output list but not on the slider labels:

![Screenshot from 2024-05-05 10-48-43](https://github.com/Rayzeq/quick-settings-audio-panel/assets/72587902/4ec39ce0-a1b3-4640-a1ea-bc64c2135473)

Is that fixable, do you think?

**Comment by Rayzeq** [comment]
Compatibility added 👍 (in version 49)

**Comment by kabe-inc** [comment]
Legend!
