### ISSUE TITLE
[Feature request] add a setting related to media panel border-radius...

### ISSUE THREAD

**Issue by dasnoopy** [Rayzeq/quick-settings-audio-panel#42]
Hi, I'm running gnome v46.1  with a customized gnome-shell theme...

Could be possible implement  an option  to set the border-radius of media panel or e.g.  an option like  : [` ] follow theme style `settings  that will override the border-radius defined in the stylesheet.css file?.

![screenshoot](https://github.com/Rayzeq/quick-settings-audio-panel/assets/296922/8fefb2de-7cf8-46c2-bd8a-dcaf9230beea)

Thanks
Andrea

**Comment by Rayzeq** [comment]
I think I can do that by disabling the custom css that my extension have (which overrides `border-radius`), but can you share the theme you're using so I can check if it detects the mpris player correctly ?

**Comment by dasnoopy** [comment]
Here it is : [https://github.com/dasnoopy/MyAdwaita-Colors](https://github.com/dasnoopy/MyAdwaita-Colors)
you can grab only the gnome-shell theme and ignore all the rest : it's a poor tentative to have accent colors in gnome :-)

Thanks
Andrea

**Comment by Rayzeq** [comment]
It seems disabling the css make the theme works, there is now an option to do that (it's off by default) in version 41

**Comment by dasnoopy** [comment]
Thanks for implementing the option...

Unfortunately, I noticed a side effect when enable new option : there is an issue when the title of song or streaming that you are playing is too long:

![screenshot](https://github.com/Rayzeq/quick-settings-audio-panel/assets/296922/30a96479-7836-4370-a6e5-52c80a2edc96)

This is not gnome-shell dependent (it occurs also with default adwaita theme)

Thanks
Andrea

**Comment by Rayzeq** [comment]
Well, I guess the size limit for the text have no reason to be overridden by a theme, so I excluded it from the new setting, which means it will always be enabled.
