### ISSUE TITLE
Unable to change audio output even with pactl installed

### ISSUE THREAD

**Issue by Raeitus** [Rayzeq/quick-settings-audio-panel#45]
**Describe the bug**
Unable to change output of device per application.

Per the settings under **Create applications mixer**, it mentions:

> `pactl` was not found, you won't be able to change the output device per application

My system shows that I have `pactl` installed:

```
pacman -F pactl 
extra/gstreamer-docs 1.24.3-1
    usr/share/doc/gstreamer/html/assets/js/search/pactl
extra/libpulse 17.0-3 [installed]
    usr/bin/pactl
    usr/share/bash-completion/completions/pactl
```

```
pactl --version
pactl 17.0
Compiled with libpulse 17.0.0
Linked with libpulse 17.0.0
```

**Compatibility**
Issue is the same even without other extensons

**Screenshots**
![image](https://github.com/Rayzeq/quick-settings-audio-panel/assets/22500082/2974dbc0-a3f6-4be5-808b-25b57a6cf0b7)
![image](https://github.com/Rayzeq/quick-settings-audio-panel/assets/22500082/7ed945d8-e307-4a05-a6b8-0ca08ea6be18)

**Desktop (please complete the following information):**
 - OS (distribution): Arch Linux
 - Gnome shell version: 46
 
**Additional context**

I did read #43 , but it looks like I only need to have `pactl` installed per that issue

**Comment by Rayzeq** [comment]
My code was broken and always displayed the warning message, that's fixed !
On your screenshot it seems that you only have one output device (because there is no arrow to change device on the master volume slider), which is why there is no arrow on application sliders either.
Please reopen if I'm wrong
