### ISSUE TITLE
[Bug]: Message »pactl was not found« in Settings > Create applications mixer ~ even though it is clearly installed

### ISSUE THREAD

**Issue by NA0341** [Rayzeq/quick-settings-audio-panel#47]
**Description:**
In the Extension's Settings under `Create applications mixer` there's a message saying `pactl was not found, you won't be able to change the output device per application`, even though it is clearly installed (I can run it in the Terminal).

But there's something odd: Although it is clearly installed, it's not recognized by the package manager (pacman). It's also not installed from the AUR or Flatpak.

`whereis` states the default location and also the manpage:

```
$ whereis pactl
pactl: /usr/bin/pactl /usr/share/man/man1/pactl.1.gz
```

To me it looks as if it is in the $PATH. So if Quick Settings Audio Panel would be using the $PATH environment variable instead of a fixed path, such issues should not arise. (?)

**Compatibility**
Does this issue arise when all other extensions are disabled ?
Issue is still present with othter extensions disabled.

# System Details Report

## Report details
- **Date generated:**                              2024-06-24 10:04:59

## Hardware Information:
- **Hardware Model:**                              Dell Inc. Latitude E5470
- **Memory:**                                      16,0 GiB
- **Processor:**                                   Intel® Core™ i5-6300HQ × 4
- **Graphics:**                                    Intel® HD Graphics 530 (SKL GT2)
- **Disk Capacity:**                               256,1 GB

## Software Information:
- **Firmware Version:**                            1.34.3
- **OS Name:**                                     Manjaro Linux
- **OS Build:**                                    rolling
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.1.92-1-MANJARO

**Comment by Rayzeq** [comment]
ooooops, I already fixed this issue, but I forgot to publish a new version, the warning shouldn't appear anymore

**Comment by NA0341** [comment]
Yes! The warning's gone 👍
I can now change both the Output and Input device.

Thank You!

But I am not able to `change the output device per application` ~ as the warning message said when `pactl` was "missing":

![image](https://github.com/Rayzeq/quick-settings-audio-panel/assets/26059513/48fcc5eb-0e65-4717-a8a1-9b5d8d6627a7)

To my understanding, there should be an arrow by the application sliders to change their output device. That would be the most important function to me.

---
PS: I also had some new improvement ideas. I added them to the list in #49

**Comment by Rayzeq** [comment]
That's because you only have one output device: the "Headphones" and "Speakers" are two ports on the same sound card, so they can't be used at the same time.

**Comment by NA0341** [comment]
Oh okay. Thank you for clarifying that :star2:
