### ISSUE TITLE
General UI/UX - Improvements

### ISSUE THREAD

**Issue by NA0341** [Rayzeq/quick-settings-audio-panel#49]
# List of UI & UX - Improvements

This list is to have one central place for Improvement Suggestions.
Since in most cases such suggestions are very simple and don't really need an extra thread for it.

:gem: **Suggestions Welcome** :heart:

+ [x] Setting to Make the Panel into an independent Panel in the Dock. Outside of the System Panel.
+ [ ] Setting to Move the Panel to the left, center, right.
+ [ ] [Bug]: Playback Controls expand under the below Element when outfolded via the Button.

![image](https://github.com/Rayzeq/quick-settings-audio-panel/assets/26059513/ddb08213-f033-4f18-b5f0-6f91e4236c24)

+ [x] Setting to manually set the Exec Path for `pactl` if it cannot be found.
+ [x] #48
+ [ ] Setting to make the volume sliders "snap" to certain levels. I suggest 50% & 100% ~ and maybe 25% too.

**Comment by Rayzeq** [comment]
> Setting to Move the Panel to the left, center, right.

What do you mean exactly by that ? Moving the icon to access the panel (as by first proposal) ?
If you mean moving the whole quick settings, this is already possible (well, you'll need another extension to move the button in the titlebar, but you can still align panels to the left or the right). If you mean moving the audio panel relative to the main panel, this also possible, you just need to drag and drop the panel (although it certainly won't be aligned to the edge of the screen)
What exactly do you mean by that ? Move the icon to access the panel (as per the first suggestion) ?
If you mean moving the whole quick settings, that's already possible (you'll need another extension to move the button in the title bar, but you can already align the panels left or right). If you want to move the audio panel relative to the main panel, that's also possible, just drag and drop the panel (although it certainly won't be aligned with the edge of the screen).

**Comment by Rayzeq** [comment]
> Setting to make the volume sliders "snap" to certain levels. I suggest 50% & 100% ~ and maybe 25% too.

This seems really difficult to do, as I'd have to hook quite deep into the rendering and event handling code for the sliders. I've looked a bit into the code that handles "overamplification", and it doesn't allow you to add marks, nor does it do snapping.
