### ISSUE TITLE
Option to limit maximum width

### ISSUE THREAD

**Issue by HubKing** [Rayzeq/quick-settings-audio-panel#5]
It seems that the "new panel" and the existing panel get widened to fit the longest sound source name, which happened to be, in my case, an instance of MPV that has a long video file name in the title. There should be a limit in the width.

With this extension
![image](https://github.com/Rayzeq/quick-settings-audio-panel/assets/10900489/86e2f5b5-e855-400a-9fc4-1b13bbbcb7cb)

Without this extension
![image](https://github.com/Rayzeq/quick-settings-audio-panel/assets/10900489/aa7af9f4-f7f4-4fa3-a53a-323d91ac9cd0)

**Comment by Rayzeq** [comment]
Fixed in version 9 👍

**Comment by HubKing** [comment]
> Fixed in version 9 +1

Yeah, it was fixed. Thanks.

By the way, I saw the changes, and was this caused by a missing semicolon? Just curious, as a some-sort-of programmer myself. I have made even stupider bugs like adding a semicolon after the if parenthesis.

![image](https://github.com/Rayzeq/quick-settings-audio-panel/assets/10900489/038967d9-6ab7-462b-886e-910d2e73624e)
