### ISSUE TITLE
Quick settings dialog is displayed on the wrong display in the multi-monitor setup with Dash to Panel extension

### ISSUE THREAD

**Issue by arg0NNY** [Rayzeq/quick-settings-audio-panel#50]
**Describe the bug**
Quick settings dialog is displayed on the wrong display in the multi-monitor setup with Dash to Panel extension enabled. I noticed it after updating to v56, it was working fine on the previous versions.

**Compatibility**
Dash to Panel v62

**Screenshots**
When disabled:
![image](https://github.com/Rayzeq/quick-settings-audio-panel/assets/52377180/3f32ab57-2aa3-4711-bd6c-76da6bef76af)

When enabled:
![image](https://github.com/Rayzeq/quick-settings-audio-panel/assets/52377180/aaced4b3-029b-420b-ad4f-c77c1f4293dc)

The result is the same when you set the dash to display on all monitors in the Dash to Panel settings. It always shows up on the top display, even if triggered from the bottom one.

Here is my monitor configuration, the bottom monitor is set as a primary display:
![image](https://github.com/Rayzeq/quick-settings-audio-panel/assets/52377180/e3ee06f7-0c2d-4e51-a32c-c39d909484d0)

**Desktop:**
 - OS (distribution): Ubuntu 24.04
 - Gnome shell version: 46.0

**Comment by Rayzeq** [comment]
This is fixed by version v57
