### ISSUE TITLE
Renaming & hiding devices

### ISSUE THREAD

**Issue by evert** [Rayzeq/quick-settings-audio-panel#53]
This may be out of scope for this add-on, but I thought I would give it a shot!

I do a lot of switching between 2-3 devices, but most of these are not useful devices to me:

![image](https://github.com/user-attachments/assets/af4ab83a-8a7b-4006-aa12-8e74556c5099)

It would be nice if I could hide some devices permanently, and also rename some devices to be more recognizable like "Headphones". 

Either way, thanks for this add-on it's top notch!

**Comment by Rayzeq** [comment]
You can use [Quick Settings Audio Devices Renamer](https://extensions.gnome.org/extension/6000/quick-settings-audio-devices-renamer/) and [Quick Settings Audio Devices Hider](https://extensions.gnome.org/extension/5964/quick-settings-audio-devices-hider/) for that.
It doesn't look like you're using it, but just in case you are, be aware that these extensions won't affect the sliders created by the "Per-device volume sliders" option.
