### ISSUE TITLE
Feature Request: Add Audio Balance Slider

### ISSUE THREAD

**Issue by azomDev** [Rayzeq/quick-settings-audio-panel#54]
Gnome shell version: 46.4

Hi there,

Thank you for the fantastic work on this extension!

I have a small request: could you consider adding a setting to have a slider to adjust the left/right audio balance? My earphones have an issue with balance, and having this feature would make it much easier for me to manage the audio than to always go into the settings to change the balance.

If this is something you’d be open to considering, I'd be more than happy to provide any additional information or assist in any way I can!

**Comment by Rayzeq** [comment]
This is now available in version 59 !

Note that due to limitations of gnome's libraries:
- You need the `pactl` command for the slider to work
- The slider will not be updated if the balance is modified using something other than this extension
- It's a bit laggy when moving the slider

**Comment by azomDev** [comment]
Thanks for the fast reponse!

I tried updating it but it did not work. Went to see the page of the extensions at https://extensions.gnome.org/extension/5940/quick-settings-audio-panel/ and found that the version 59 has been rejected..,

**Comment by Rayzeq** [comment]
I've published a new version which should (hopefully) pass the review.
Thanks to the reviewer's advice, the lag when moving the slider is gone.

**Comment by azomDev** [comment]
Hey! I know this feature was added a while ago, but I just wanted to say thank you for adding it! Because of it, I’m still able to use my older earbuds with a balance issue easily :)
