### ISSUE TITLE
PWA Support

### ISSUE THREAD

**Issue by Malix-Labs** [Rayzeq/quick-settings-audio-panel#55]
## Feature Request

Currently, PWA sound cannot be separated
They are all mastered by the Browser sound

It would be sweet to have PWA support in this great extension

## Logs

Gnome shell version: 46.4

**Comment by Rayzeq** [comment]
This is not possible, because browsers doesn't create a separate audio stream.

**Comment by Rayzeq** [comment]
On Linux, browsers use pulseaudio to make sound, whereas they use winapi on Windows, so I guess there are differences in implementations that make it possible on Windows.

**Comment by Rayzeq** [comment]
Actually, it's possible on firefox, which give the name of the tab to the audio stream.
![image](https://github.com/user-attachments/assets/e74275ab-74ad-4a17-8379-93ba0e17949c)

The first stream is youtube, not pwa, the second one is spotify, pwa.
Note that firefox doesn't support PWAs, you'll need to use [this extension](https://addons.mozilla.org/en-US/firefox/addon/pwas-for-firefox/)

**Comment by Malix-Labs** [comment]
Wouldn't that also be possible with Chromium ?

**Comment by Rayzeq** [comment]
There were two issues on Chromium to do this, but they were both closed:
https://issues.chromium.org/issues/41346246
https://issues.chromium.org/issues/41391680

**Comment by Malix-Labs** [comment]
Okay, thanks !

_btw, I think it would be nice to change this issue to closed as not planned instead of close as completed_
