### ISSUE TITLE
a way to rename the audio outputs

### ISSUE THREAD

**Issue by mohamed776k776** [Rayzeq/quick-settings-audio-panel#60]
GNOME Shell 46.5

i would like a way to rename my audio outputs when i enable "Create per-device volume sliders"
i am using an extension called "Quick Settings Audio Devices Renamer" which works for the master slider but not the per-device sliders 
i would like the per-device sliders to match the master slider and i do not mined inputing the names manually to the extension so that i have the same custom name for every device within the system
thanks a lot for the amazing extension <3

**Comment by Rayzeq** [comment]
Per-device sliders are now compatible with Quick Settings Audio Devices Renamer in version 65 !
