### ISSUE TITLE
Boosting volume past 100%

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [Rayzeq/quick-settings-audio-panel#61]
Gnome shell version: 45.5

**Describe the feature you'd like**

Sometimes I want to increase the volume past the 100%, boosting the audio. I can increase the volume on speakers or the headset, but up to a certain point obviously. It is possible to set the volume past 100% on most audio backends, and such a feature would be very welcome.

**Comment by Rayzeq** [comment]
It's already possible, you just need to enable the option in the gnome settings
![a](https://github.com/user-attachments/assets/d63fce77-0080-4f1e-8fb7-b63d17fd6337)
It also works for per-device sliders, but if you want this option to work for other kind of sliders (like the application mixer), please reopen this issue

**Comment by JohnTheCoolingFan** [comment]
I had to go to dconf to enable this, for some reason the option just wasn't there for me (pipewire). Thanks to [this EndeavourOS thread](https://forum.endeavouros.com/t/i-just-figured-out-how-to-turn-on-overamplification-in-gnome-to-put-the-volumes-above-100-natively/53429) I found the setting, and it works per-application even. Sorry for the issue, I thought it was an extension limitation.

**Comment by Rayzeq** [comment]
Ah, I thought this was part of gnome, but it might be added by ubuntu.
I don't understand why, but Gnome seems to like to create options without an easy way to enable them.
