### ISSUE TITLE
Quick Settings is forced to right

### ISSUE THREAD

**Issue by skewty** [Rayzeq/quick-settings-audio-panel#62]
**Describe the bug**
Quick Settings is forced to right; it should not override the horizontal position.
I would prefer it to remain closer to where I clicked, not 30cm / 1ft away.

**Compatibility**
Probably, but one would not see the bug because by default forced right would
look like the normal position.

If so, which extension(s) are causing the issue ?

Dash-to-Panel (panel is set to 40% width and centered on ultra-wide monitor).

**Screenshots**
![image](https://github.com/user-attachments/assets/000c8d32-d908-4c69-b1fa-785346c0a360)

**Desktop (please complete the following information):**
 - OS (distribution): Fedora 41
 - Gnome shell version: 47.1

**Additional context**

**Comment by Rayzeq** [comment]
From your screenshot, it seems that the "System menu" button is on the left of the screen. If it's the case, you can change the panel alignment in the QSAP settings:
![image](https://github.com/user-attachments/assets/7df961f7-935d-4919-b94b-2b23b2b33493)

But from your explanation, I guess it's more or less in the middle-right of the screen, so I'll make a setting to disable libpanel (which is responsible for the menu going all the way to the right or left). In the meantime (it shouldn't take too long) you can either put the panel in a separated indicator (which will disable libpanel), or merge the new panel in the main one (which doesn't disable libpanel, although it should, I'll fix that too).

**Comment by Rayzeq** [comment]
Version 69 of the extension has been published, it adds a new option (in **LibPanel settings** category) named 'Single-column mode', enable it to fix the issue.
