### ISSUE TITLE
Fails to load: SyntaxError: nothing to repeat @ widgets.js

### ISSUE THREAD

**Issue by FM33** [Rayzeq/quick-settings-audio-panel#64]
**Describe the bug**
The extension fails to load with error:
SyntaxError: nothing to repeat @ file:///home/fabien/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/libs/widgets.js:409:41

**Compatibility**
Does this issue arise when all other extensions are disabled ?
Yes

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04
 - Gnome shell version: 46.0

**Additional context**
Used to work before, in the same context (probably extension update).

**Comment by Rayzeq** [comment]
It means you have an invalid regex in your mixer filtering. If you have one of these characters: `.+*?^$()[]{}|\` that you intended to write literally you need to escape it with a `\` (for example `*Test*` would become `\*Test\*`).
I'll add a check to warn against invalid regexes in the settings to prevent this from happening again
