### ISSUE TITLE
I can't turn this Extension on for some reason. I get an error.

### ISSUE THREAD

**Issue by Meemonomon** [Rayzeq/quick-settings-audio-panel#65]
**Describe the bug**
I got the latest release installed (version 73)
The error I get is :

`ImportError: Unable to load file from: file:///home/ninjago/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/libs/libpanel/mixins.js (Error opening file /home/ninjago/.local/share/gnome-shell/extensions/quick-settings-audio-panel@rayzeq.github.io/libs/libpanel/mixins.js: No such file or directory)
`

**Desktop :**
 - Fedora 41
 - Gnome shell version: 47.1

**Comment by Rayzeq** [comment]
Well I forgot to stash my ongoing work when building the release 😭, I published a new version fixing it.

**Comment by Meemonomon** [comment]
Thanks. It's working now.
