### ISSUE TITLE
Value is not a string, cannot convert to UTF-8

### ISSUE THREAD

**Issue by HaydenCLUU** [Rayzeq/quick-settings-audio-panel#66]
Error: Value is not a string, cannot convert to UTF-8
Caused by: Error: Invalid element in string array

It just happened out of nowhere. the sliders work as normal but the media is not appearing anymore. Im on gnome 47 with fedora 41. it worked fine the first boot.
![Screenshot From 2024-12-20 20-40-31](https://github.com/user-attachments/assets/2ba7ca40-a097-4f00-9091-bcffe8e16cb7)
![Screenshot From 2024-12-20 20-41-30](https://github.com/user-attachments/assets/d654e7ef-fecf-4183-bd28-dd9bbe9090f8)

**Comment by Rayzeq** [comment]
Why did you close the issue ?
Did you find a workaround, or was it a mistake on your part (I'm guessing you edited the configuration using external software like dconf) ?

**Comment by HaydenCLUU** [comment]
It was one setting that fixed it. When you enable "add a balance slider" it somehow broke the extension

**Comment by Rayzeq** [comment]
Maybe it's an issue with `pactl`, but I can't know without more details. If you want this issue fixed, send the logs (you can use this command to get the them: `journalctl /usr/bin/gnome-shell | cat`). If you don't really care, you can re-close the issue.
