### ISSUE TITLE
Feature request: Ability to hide certain mixers

### ISSUE THREAD

**Issue by ludvigng** [Rayzeq/quick-settings-audio-panel#7]
Hello!

Certain applications (or web apps) don't play nice with pulseaudio, creating several separate mixers. It would be nice if we could hide these from the audio control panel, since they take up quite a lot of unnecessary space:
![image](https://github.com/Rayzeq/quick-settings-audio-panel/assets/50339757/e9f45eba-1822-4876-9cb0-d601343857d7)

https://github.com/qwreey75/quick-settings-tweaks does this by letting the user supply a string, with rules to either block matching strings in the mixer, or only allowing matching strings. This is probably a bit overkill, but it would be nice to have some way of hiding some of the extraneous mixers at least. :)

**Comment by Rayzeq** [comment]
Now available in version 11

**Comment by ludvigng** [comment]
Super nice, thank you!
